### ISSUE TITLE
npm install latest issue - fixed by defining version 6.14.15

### ISSUE THREAD

**Issue by JoelWakefield** [MicrosoftDocs/mslearn-tailspin-spacegame-web-deploy#116]
Hello!

I encountered a small issue that I was able to resolve, but I'm curious to learn better/other solutions.

## ISSUE
I encountered an issue during the Build stage, at the install npm task. 

First, the logs mentioned...
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```

Then there were some deprecation warnings...
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.2: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
```

... followed by the gut punching...
```
npm ERR! code 1
```

... and after that, a <i>rootin' tootin' <b>TON</b></i> of errors.

**Comment by JoelWakefield** [comment]
ok, these changes are not working now. honestly, I don't know what's up. Sometimes the - task: Npm@1 works, other times it crashes the pipeline. It could have sometime to do with current azure devops issues that have happened recently.

**Comment by JoelWakefield** [comment]
Okaaaaay. It looks like there's some updates to Npm@1 task that caused this; long story short, Npm@1 will install v14 of node, breaking some dependencies in the package-lock.json file. One can get around this by installing node v12 specifically before the npm install. 

So, now I run the NodeTool@0 task before the Npm@1 task, like so. 
```
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false
```

This seems to have stabilized things.

**Comment by tstanfield** [comment]
@JoelWakefield I hit the same snag and your proposed solution worked. Should we reopen this issue and propose this change in a PR?
