### ISSUE TITLE
NPM install issue in Azure DevOps due to node-sass version

### ISSUE THREAD

**Issue by bryansonofpatt** [MicrosoftDocs/mslearn-tailspin-spacegame-web-deploy#128]
I'm working through the [AZ-400: Define and implement continuous integration](docs.microsoft.com/en-us/learn/paths/az-400-define-implement-continuous-integration/) modules. Whenever I use a new branch off any of the mslearn-tailspin-spacegame-web... repos, I get npm install errors in ADO due to an outdated node-sass version in the package.json. It downloads as "node-sass": "^4.14.1". When I update it to "node-sass": "6.0.1" builds fine. 
Thanks!

**Comment by letpapatype** [comment]
@bryansonofpatt THANK YOU!

**Comment by tpetchel** [comment]
@bryansonofpatt  - thanks for the investigation here, and sorry this broke! This should be resolved now; see #123. Thanks again!
